[app]
name = "后端开发"
# 当前环境, development（开发）、testing（测试） 或 production（生产）
env = "development"
# 监听端口号
port = 8080
version = "v0.1"

[databasse]
    [database.mysql]
    user = "Golang"
    password = "123456"
    master_host = "192.168.10.71"
    slave_host_1 = "192.168.10.72"
    slave_host_2 = "192.168.10.73"
    port = 3306
    db_name = "test"
    max_open_conns = 100
    max_idle_conns = 20
    timeout = "15s"

    [database.redis]
    master_host = "192.168.10.74"
    slave_host_1 = "192.168.10.75"
    slave_host_1 = "192.168.10.76"
    port = 6379
    password = "redispass"

[log]
version = "v0.1"
level = "test"
path = "E:/var/log/star-PPT/"
maxSize = 100
maxBackup = 5
maxAge = 30
compress = false

